version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: progravis-db
    restart: always
    environment:
      POSTGRES_USER: karen
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: progravis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
